// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdbvd2apCc_7yitGE78vPwyy_eASjFLeA',
    appId: '1:89503229135:web:559949099fc164019c83ba',
    messagingSenderId: '89503229135',
    projectId: 'belajar-crud-firebase-12345',
    authDomain: 'belajar-crud-firebase-12345.firebaseapp.com',
    storageBucket: 'belajar-crud-firebase-12345.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoisQIfE0pUWmxxnhHOD15IZx8hOueAmc',
    appId: '1:89503229135:android:18dbd7962ec549659c83ba',
    messagingSenderId: '89503229135',
    projectId: 'belajar-crud-firebase-12345',
    storageBucket: 'belajar-crud-firebase-12345.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs726ctm4FINlqUSowy7yn7L6G7-H9i80',
    appId: '1:89503229135:ios:d944a6a466f3b4819c83ba',
    messagingSenderId: '89503229135',
    projectId: 'belajar-crud-firebase-12345',
    storageBucket: 'belajar-crud-firebase-12345.firebasestorage.app',
    iosBundleId: 'com.example.belajarCrudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs726ctm4FINlqUSowy7yn7L6G7-H9i80',
    appId: '1:89503229135:ios:d944a6a466f3b4819c83ba',
    messagingSenderId: '89503229135',
    projectId: 'belajar-crud-firebase-12345',
    storageBucket: 'belajar-crud-firebase-12345.firebasestorage.app',
    iosBundleId: 'com.example.belajarCrudFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdbvd2apCc_7yitGE78vPwyy_eASjFLeA',
    appId: '1:89503229135:web:f642e23edd8ae8d19c83ba',
    messagingSenderId: '89503229135',
    projectId: 'belajar-crud-firebase-12345',
    authDomain: 'belajar-crud-firebase-12345.firebaseapp.com',
    storageBucket: 'belajar-crud-firebase-12345.firebasestorage.app',
  );

}