// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4FQDT2wvsDgkfaxG6hqisptZiMErMj-k',
    appId: '1:641842615426:web:55e0eb86ac9a4ca5dd509b',
    messagingSenderId: '641842615426',
    projectId: 'belajar-auth-firebase-12345',
    authDomain: 'belajar-auth-firebase-12345.firebaseapp.com',
    storageBucket: 'belajar-auth-firebase-12345.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhKBYOpmymQxjgEO1Qnvz6I39lXZd8h1M',
    appId: '1:641842615426:android:3ce4800445e7f14cdd509b',
    messagingSenderId: '641842615426',
    projectId: 'belajar-auth-firebase-12345',
    storageBucket: 'belajar-auth-firebase-12345.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4FQDT2wvsDgkfaxG6hqisptZiMErMj-k',
    appId: '1:641842615426:web:245bb57c22e1ac9bdd509b',
    messagingSenderId: '641842615426',
    projectId: 'belajar-auth-firebase-12345',
    authDomain: 'belajar-auth-firebase-12345.firebaseapp.com',
    storageBucket: 'belajar-auth-firebase-12345.firebasestorage.app',
  );
}
